image:
  file: Dockerfile
  
ports:
  - port: 8001
  
tasks:
  -  command: mkdir /workspace/my-gitpod-ionic-cordova/logs                              &&
              touch /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt       &&
       
       
              echo "Starting .gitpod.yml installation" &>>  /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt  &&  
              
              echo "Set bash files to runable"         &>>  /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt  &&                 
              chmod +x a01-electron-create.sh                                                                               &&      
              
              
            
             

          
              echo "Starting Apache"                   &>>  /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt  &&   
              apachectl start                                                                                               &&
              gp await-port 8001                                                                                            && 
              gp preview $(gp url 8001)                                                                                     &&
              
              
              
              echo "Ending .gitpod.yml installation"  &>>   /workspace/my-gitpod-ionic-cordova/logs/gitpod-install-log.txt    
              
              
     
